import type { Axis, SurveyQuestion, Topic } from "@parallax/shared";

export const SURVEY_QUESTIONS: SurveyQuestion[] = [
  {
    id: "q1",
    text: "Capital gains should be taxed at the same rate as wages.",
    axis: "econ",
    weight: 1,
    active: true,
  },
  {
    id: "q2",
    text: "The free market allocates resources better than government planning.",
    axis: "econ",
    weight: 1,
    active: true,
  },
  {
    id: "q3",
    text: "National interest should come before international cooperation.",
    axis: "dipl",
    weight: 1,
    active: true,
  },
  {
    id: "q4",
    text: "Countries should prioritize global agreements over unilateral action.",
    axis: "dipl",
    weight: -1,
    active: true,
  },
  {
    id: "q5",
    text: "Government surveillance is acceptable if it reduces crime.",
    axis: "civil",
    weight: -1,
    active: true,
  },
  {
    id: "q6",
    text: "Individual privacy should rarely be compromised for security.",
    axis: "civil",
    weight: 1,
    active: true,
  },
  {
    id: "q7",
    text: "Social change should happen gradually, not rapidly.",
    axis: "scty",
    weight: -1,
    active: true,
  },
  {
    id: "q8",
    text: "Society should embrace progressive reforms even when they disrupt tradition.",
    axis: "scty",
    weight: 1,
    active: true,
  },
  {
    id: "q9",
    text: "Wealthy individuals and corporations should pay higher taxes to fund public services.",
    axis: "econ",
    weight: -1,
    active: true,
  },
  {
    id: "q10",
    text: "Immigration strengthens a nation's economy and culture.",
    axis: "dipl",
    weight: 1,
    active: true,
  },
];

export const TOPICS: Topic[] = [
  {
    id: "topic-economy",
    slug: "economy-and-inequality",
    title: "Economy and inequality",
    question: "Economy and inequality",
    description: "Markets, taxes, public services, wealth, and how much government should shape economic outcomes.",
    primaryAxis: "econ" as Axis,
    active: true,
  },
  {
    id: "topic-world",
    slug: "national-interest-and-global-cooperation",
    title: "National interest and global cooperation",
    question: "National interest and global cooperation",
    description: "Foreign policy, immigration, sovereignty, alliances, and where a country should draw its obligations.",
    primaryAxis: "dipl" as Axis,
    active: true,
  },
  {
    id: "topic-rights",
    slug: "privacy-security-and-civil-liberties",
    title: "Privacy, security, and civil liberties",
    question: "Privacy, security, and civil liberties",
    description: "Surveillance, policing, safety, speech, and when individual rights should limit state power.",
    primaryAxis: "civil" as Axis,
    active: true,
  },
  {
    id: "topic-change",
    slug: "social-change-and-tradition",
    title: "Social change and tradition",
    question: "Social change and tradition",
    description: "Culture, reform, stability, identity, and how quickly society should change its norms.",
    primaryAxis: "scty" as Axis,
    active: true,
  },
  {
    id: "topic-government",
    slug: "government-responsibility-and-public-life",
    title: "Government responsibility and public life",
    question: "Government responsibility and public life",
    description: "Healthcare, climate, regulation, public investment, and what citizens should expect from institutions.",
    primaryAxis: "econ" as Axis,
    active: true,
  },
];
